### ISSUE TITLE
Do not prescreen file types

### ISSUE THREAD

**Issue by avidrissman** [nmrshll/gphotos-uploader-cli#66]
Why do you attempt to screen what's uploaded? I can imagine that in a scenario where the images are mixed in with lots of other file types, sure, but in the case where I'm passing in a photos folder full of only photos, I'd really like an option to bypass all filetype comparing and just *try* to upload everything, and if the server fails to take it, make a note that it was uploaded and don't try again.

This would solve prescreening issues like #59 and #65.

**Comment by avidrissman** [comment]
I just realized that in my situation, where I’m mounting into docker a directory from my Synology littered with `@eaDir` metadata directories, this would require some kind of regex filter to exclude paths.

**Comment by pacoorozco** [comment]
Hi @avidrissman 

The idea of prescreening files is to avoid useless calls to the Google Photos API, but in this case, where the user know that only some files are supported, I'll suggest to remove prescreening and deal with API response errors in case of invalid files.

This could connect with #44 in order to avoid files that, for sure, are going to become failed on upload.

What do you think? Should we remove prescreening? **Please share your feedback**

**Comment by rfgamaral** [comment]
Instead of removing prescreening why not move the prescreening option to the configuration file (with sensible defaults)? Some sort of "whitelisted extensions or filenames".

That way we would allow anyone to change what is allowed to be uploaded and what should be excluded. We could even have an option that would mean "try to upload anything without exclusions".

**Comment by avidrissman** [comment]
I would be in favor of an allowlist/blocklist. Basically, anything that helps me not have to fight to get my stuff uploaded.

**Comment by pacoorozco** [comment]
@rfgamaral @avidrissman If i've read good, I think these allowlist/blocklist could be implemented as `excludePattern` and `includePattern` from #44 Am I right?

**Comment by avidrissman** [comment]
Yep; the allow/blocklist from #44 would be great.

**Comment by rfgamaral** [comment]
I think you can close this :)

**Comment by avidrissman** [comment]
This is different than #44.

44 is about having a blocklist/allowlist. This issue is about removing file type screening.

**Comment by rfgamaral** [comment]
Which is the same thing. If you implement a block/allow list, you are effectively removing the current file type screening.

**Comment by avidrissman** [comment]
Sure.
