### ISSUE TITLE
Cannot find package "google.golang.org/api/photoslibrary/v1"

### ISSUE THREAD

**Issue by gregadunbit** [nmrshll/gphotos-uploader-cli#79]
I am not able to install since of the missing package from above.

Trying to do:
go get -u  -> fails with package google.golang.org/api/photoslibrary/v1: cannot find package "google.golang.org/api/photoslibrary/v1" in any of:

make build

**Comment by pacoorozco** [comment]
Hi,Please review installation instructions... it's not possible to use go get when you ate using a "vendor" library and go mod. PacoEl 29 jun. 2019 6:29, gregadunbit <notifications@github.com> escribió:I am not able to install since of the missing package from above.
Trying to do:
go get -u  -> fails with package google.golang.org/api/photoslibrary/v1: cannot find package "google.golang.org/api/photoslibrary/v1" in any of:
make build
